<?php

namespace App\Services\Evidence;

use Mpdf\Mpdf;
use Mpdf\Output\Destination;

/**
 * Renders an IncidentEvidencePackage as a server-side PDF.
 * Treats all incident content as untrusted text — escapes HTML, never fetches remote content.
 */
class EvidencePackagePdfRenderer
{
    public function render(IncidentEvidencePackage $package): string
    {
        $tempDir = storage_path('app/mpdf-temp');
        if (! is_dir($tempDir)) {
            mkdir($tempDir, 0755, true);
        }

        $mpdf = new Mpdf([
            'mode' => 'utf-8',
            'format' => 'A4',
            'tempDir' => $tempDir,
            'default_font' => 'dejavusans',
            'autoScriptToLang' => true,
            'autoLangToFont' => true,
        ]);

        $mpdf->SetTitle('Community Shield Incident Evidence Package');
        $mpdf->SetAuthor('UmmahOS Community Shield');
        $mpdf->WriteHTML($this->html($package));

        return $mpdf->Output('', Destination::STRING_RETURN);
    }

    private function html(IncidentEvidencePackage $package): string
    {
        $data = $package->toArray();
        $incident = $data['incident'] ?? [];
        $evidence = $data['evidence'] ?? [];
        $ai = $data['ai_analysis'] ?? [];
        $human = $data['human_review'] ?? [];
        $reporting = $data['reporting_route'] ?? [];
        $safety = $data['safety_privacy_notes'] ?? [];
        $disclaimers = $data['disclaimers'] ?? [];
        $outcomeTracking = $data['outcome_tracking'] ?? [];
        $meta = $data['package'] ?? [];
        $original = $evidence['original_item'] ?? [];
        $currentAi = $ai['current'] ?? [];
        $decision = $human['decision'] ?? [];
        $escalation = $human['escalation'] ?? [];

        $sections = [];

        $sections[] = '<h1>COMMUNITY SHIELD</h1>';
        $sections[] = '<h2>INCIDENT EVIDENCE PACKAGE</h2>';
        $sections[] = $this->kv([
            'Package version' => (string) ($meta['package_version'] ?? '1'),
            'Schema version' => (string) ($meta['schema_version'] ?? '1'),
            'Generated at' => $this->display($meta['generated_at'] ?? null),
            'Generated by' => $this->display(data_get($meta, 'generated_by.name')),
            'Organization' => $this->display(data_get($meta, 'organization.name')),
            'Incident reference' => $this->display($incident['reference'] ?? null),
        ]);

        $sections[] = '<h3>Incident Summary</h3>';
        $sections[] = $this->kv([
            'Platform' => $this->display($incident['platform'] ?? null),
            'Content type' => $this->display($incident['content_type'] ?? null),
            'Visibility' => $this->display($incident['visibility'] ?? null),
            'Language' => $this->display($incident['language'] ?? null),
            'Submitted' => $this->display($incident['submitted_at'] ?? null),
            'Observed' => $this->display($incident['observed_at'] ?? null),
            'Original posted' => $this->display($incident['original_item_posted_at'] ?? null),
            'Status' => $this->display($incident['status'] ?? null),
            'Review outcome' => $this->display($incident['review_outcome'] ?? null),
            'Source URL' => $this->display($incident['source_url'] ?? null),
        ]);
        if (! empty($incident['description'])) {
            $sections[] = '<p><strong>Description</strong></p>'.$this->para($incident['description']);
        }

        $sections[] = '<h3 class="evidence">1. SOURCE EVIDENCE — ORIGINAL ITEM</h3>';
        $sections[] = $this->kv([
            'Title' => $this->display($original['title'] ?? null),
            'Author' => $this->display($original['author'] ?? null),
            'Posted at' => $this->display($original['posted_at'] ?? null),
            'Observed at' => $this->display($original['observed_at'] ?? null),
            'Reference' => $this->display($original['reference_url'] ?? null),
        ]);
        $sections[] = '<p><strong>Content</strong></p>'.$this->para($original['content'] ?? null);

        $sections[] = '<h3 class="evidence">2. SOURCE EVIDENCE — CONTEXT</h3>';
        $sections[] = $this->para($evidence['surrounding_context'] ?? null);

        $sections[] = '<h3 class="evidence">3. SOURCE EVIDENCE — REPLIES</h3>';
        $replies = $evidence['replies'] ?? [];
        if ($replies === []) {
            $sections[] = '<p class="muted">No replies recorded.</p>';
        } else {
            foreach ($replies as $index => $reply) {
                $sections[] = '<p><strong>Reply '.($index + 1).'</strong> · '
                    .$this->e($this->display($reply['author'] ?? null))
                    .' · '.$this->e($this->display($reply['posted_at'] ?? null)).'</p>';
                $sections[] = $this->para($reply['content'] ?? null);
            }
        }

        $sections[] = '<h3 class="related">4. RELATED EVIDENCE</h3>';
        $related = $evidence['related_items'] ?? [];
        if ($related === []) {
            $sections[] = '<p class="muted">No related items recorded.</p>';
        } else {
            foreach ($related as $item) {
                $sections[] = $this->kv([
                    'Platform' => $this->display($item['platform'] ?? null),
                    'Content type' => $this->display($item['content_type'] ?? null),
                    'Reference' => $this->display($item['reference_url'] ?? null),
                    'Observed' => $this->display($item['observed_at'] ?? null),
                ]);
                $sections[] = $this->para($item['description'] ?? null);
            }
        }

        $sections[] = '<h3 class="reporter">REPORTER-PROVIDED CONTEXT</h3>';
        $sections[] = $this->para(data_get($evidence, 'reporter_notes.notes'));

        $sections[] = '<h3 class="ai">5. AI CONTEXT ANALYSIS — ADVISORY</h3>';
        $sections[] = '<p class="disclaimer">'.$this->e($disclaimers['ai'] ?? '').'</p>';
        $sections[] = $this->kv([
            'Status' => $this->display($currentAi['status'] ?? null),
            'Provider' => $this->display($currentAi['provider'] ?? null),
            'Model' => $this->display($currentAi['model'] ?? null),
            'Prompt version' => $this->display($currentAi['prompt_version'] ?? null),
            'Generated' => $this->display($currentAi['generated_at'] ?? null),
        ]);

        if (($currentAi['status'] ?? null) === 'completed') {
            $signals = $currentAi['signals'] ?? [];
            $sections[] = '<p><strong>Potential signals</strong></p>';
            if ($signals === []) {
                $sections[] = '<p class="muted">None recorded.</p>';
            } else {
                $sections[] = '<ul>';
                foreach ($signals as $signal) {
                    $name = is_array($signal) ? ($signal['name'] ?? 'signal') : (string) $signal;
                    $desc = is_array($signal) ? ($signal['description'] ?? '') : '';
                    $sections[] = '<li><strong>'.$this->e((string) $name).'</strong>'
                        .($desc !== '' ? ' — '.$this->e((string) $desc) : '')
                        .'</li>';
                }
                $sections[] = '</ul>';
            }

            $sections[] = $this->kv([
                'Potential classification' => $this->display(data_get($currentAi, 'classification.label')),
                'Confidence' => $this->display($currentAi['confidence'] ?? null),
                'Uncertainty' => $this->display(data_get($currentAi, 'uncertainty.level')),
                'Recommended action' => $this->display(data_get($currentAi, 'recommended_action.type')),
            ]);
            $sections[] = '<p><strong>Uncertainty explanation</strong></p>'
                .$this->para(data_get($currentAi, 'uncertainty.explanation'));
            $sections[] = '<p><strong>Alternative interpretation</strong></p>'
                .$this->para($currentAi['alternative_interpretation'] ?? null);
        } elseif (! empty($currentAi['error_message']) || ($currentAi['status'] ?? null) === 'failed') {
            $sections[] = '<p class="muted">'.$this->e($this->display($currentAi['error_message'] ?? 'Analysis could not be completed.')).'</p>';
        } else {
            $sections[] = '<p class="muted">No AI Context Analysis is available.</p>';
        }

        $sections[] = '<h3 class="ai">AI UNCERTAINTY</h3>';
        $uncertainty = $ai['uncertainty'] ?? [];
        $sections[] = $this->kv([
            'Confidence' => $this->display($uncertainty['confidence'] ?? 'Not provided'),
            'Uncertainty' => $this->display($uncertainty['uncertainty'] ?? 'Not provided'),
            'Interpretation note' => $this->display($uncertainty['interpretation_note'] ?? 'Not provided'),
        ]);

        $sections[] = '<h3 class="human">6. HUMAN REVIEW — AUTHORITATIVE</h3>';
        $sections[] = '<p class="disclaimer">'.$this->e($disclaimers['human_review'] ?? '').'</p>';

        if (($human['status'] ?? null) === 'not_yet_reviewed') {
            $sections[] = '<p><strong>Human Review Outcome:</strong> Not yet reviewed</p>';
            $sections[] = '<p class="muted">Outcome: Not available</p>';
        } else {
            if (($decision['uncertain_prominence'] ?? null) === 'UNCERTAIN') {
                $sections[] = '<p class="uncertain"><strong>Human Review Outcome: UNCERTAIN</strong></p>';
            }

            $sections[] = $this->kv([
                'Status' => $this->display($human['status'] ?? null),
                'Reviewer' => $this->display($human['reviewer'] ?? null),
                'Review started' => $this->display($human['review_started_at'] ?? null),
                'Outcome' => $this->display($human['outcome'] ?? null),
                'Human classification' => $this->display($human['human_classification'] ?? null),
                'Escalation' => ! empty($escalation['escalated']) ? 'Yes' : 'No',
                'Escalated by' => $this->display($escalation['escalated_by'] ?? null),
                'Escalated at' => $this->display($escalation['escalated_at'] ?? null),
                'Escalation reason' => $this->display($escalation['reason'] ?? null),
            ]);
            $sections[] = '<p><strong>Reviewer notes</strong></p>'.$this->para($human['notes'] ?? null);
        }

        $contextRequests = $human['context_requests'] ?? [];
        if ($contextRequests !== []) {
            $sections[] = '<h4>Additional Context Requested</h4>';
            foreach ($contextRequests as $request) {
                $sections[] = $this->kv([
                    'Requested by' => $this->display($request['requested_by'] ?? null),
                    'Requested' => $this->display($request['requested_at'] ?? null),
                    'Status' => $this->display($request['status'] ?? null),
                    'Fulfilled/resolved at' => $this->display($request['resolved_at'] ?? null),
                ]);
                $sections[] = $this->para($request['reason'] ?? null);
            }
        }

        $history = $human['history'] ?? [];
        $sections[] = '<h4>REVIEW HISTORY</h4>';
        if ($history === []) {
            $sections[] = '<p class="muted">No review actions yet.</p>';
        } else {
            $sections[] = '<ul>';
            foreach ($history as $entry) {
                $sections[] = '<li>'.$this->e($this->display($entry['at'] ?? null))
                    .' — '.$this->e($this->display($entry['summary'] ?? null))
                    .(! empty($entry['actor']) ? ' ('.$this->e((string) $entry['actor']).')' : '')
                    .'</li>';
            }
            $sections[] = '</ul>';
        }

        $sections[] = '<h3 class="evidence">7. EVIDENCE REFERENCES</h3>';
        foreach ($data['references'] ?? [] as $ref) {
            $sections[] = '<p><strong>'.$this->e((string) ($ref['label'] ?? 'Reference')).'</strong> ('
                .$this->e((string) ($ref['type'] ?? 'external')).')<br>'
                .$this->e($this->display($ref['url'] ?? null))
                .'<br><span class="muted">'.$this->e($this->display($ref['note'] ?? null)).'</span></p>';
        }

        $sections[] = '<h3 class="guidance">8. OUTCOME TRACKING</h3>';
        $sections[] = '<p class="disclaimer">'.$this->e($disclaimers['outcome_tracking'] ?? ($outcomeTracking['disclaimer'] ?? '')).'</p>';
        $outcomeReports = $outcomeTracking['reports'] ?? [];
        if ($outcomeReports === []) {
            $sections[] = '<p class="muted">No external reporting activity has been recorded yet.</p>';
        } else {
            foreach ($outcomeReports as $index => $outcomeReport) {
                $sections[] = '<h4>External Report '.($index + 1).'</h4>';
                $sections[] = $this->kv([
                    'Platform' => $this->display($outcomeReport['platform'] ?? null),
                    'Reporting channel' => $this->display($outcomeReport['reporting_channel'] ?? null),
                    'Reported' => $this->display($outcomeReport['reported_at'] ?? null),
                    'Status' => $this->display($outcomeReport['status'] ?? null),
                    'External reference' => $this->display($outcomeReport['external_reference'] ?? null),
                    'Decision' => $this->display($outcomeReport['decision'] ?? null) === 'Not provided'
                        ? 'Not yet recorded'
                        : $this->display($outcomeReport['decision'] ?? null),
                    'Outcome' => $this->display($outcomeReport['outcome'] ?? null) === 'Not provided'
                        ? 'Not yet recorded'
                        : $this->display($outcomeReport['outcome'] ?? null),
                    'Outcome source' => $this->display($outcomeReport['outcome_source'] ?? null),
                    'Verification' => $this->displayLabel($outcomeReport['verification_status'] ?? 'unverified'),
                ]);
                if (! empty($outcomeReport['outcome_summary'])) {
                    $sections[] = '<p><strong>Outcome summary</strong></p>'.$this->para($outcomeReport['outcome_summary']);
                }
                $appeals = $outcomeReport['appeals'] ?? [];
                if ($appeals !== []) {
                    $sections[] = '<p><strong>Appeals</strong></p><ul>';
                    foreach ($appeals as $appeal) {
                        $sections[] = '<li>'.$this->e($this->display($appeal['submitted_at'] ?? null))
                            .' — Appeal '.$this->e($this->display($appeal['status'] ?? null))
                            .(! empty($appeal['reason']) ? ': '.$this->e((string) $appeal['reason']) : '')
                            .'</li>';
                    }
                    $sections[] = '</ul>';
                }
            }
        }

        $sections[] = '<h3 class="guidance">9. RECOMMENDED REPORTING ROUTE</h3>';
        $sections[] = '<p class="disclaimer">'.$this->e($disclaimers['reporting'] ?? ($reporting['disclaimer'] ?? '')).'</p>';
        $sections[] = $this->kv([
            'Platform' => $this->display($reporting['platform_label'] ?? $reporting['platform'] ?? null),
            'Recommended route' => $this->display($reporting['recommended_route'] ?? null),
            'General instructions' => $this->display($reporting['general_instructions'] ?? null),
            'Safety note' => $this->display($reporting['safety_notes'] ?? null),
            'Privacy note' => $this->display($reporting['privacy_notes'] ?? null),
            'Automatic submission' => 'No — Phase 7 prepares evidence only',
        ]);

        $sections[] = '<h3 class="safety">10. SAFETY &amp; PRIVACY NOTES</h3>';
        $notes = $safety['notes'] ?? [];
        if ($notes === []) {
            $sections[] = '<p class="muted">No notes configured.</p>';
        } else {
            $sections[] = '<ul>';
            foreach ($notes as $note) {
                $sections[] = '<li>'.$this->e((string) $note).'</li>';
            }
            $sections[] = '</ul>';
        }

        $body = implode("\n", $sections);

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
body { font-family: dejavusans, sans-serif; font-size: 10pt; color: #1a1a1a; line-height: 1.45; }
h1 { font-size: 18pt; margin: 0 0 4pt; }
h2 { font-size: 13pt; margin: 0 0 12pt; color: #333; }
h3 { font-size: 11pt; margin: 16pt 0 6pt; padding: 4pt 0; border-bottom: 1px solid #999; }
h3.evidence { color: #1a4d2e; }
h3.related { color: #3d4f5f; }
h3.reporter { color: #5a4a2f; }
h3.ai { color: #5a4a00; background: #f7f3e4; padding: 6pt; border-bottom: 0; }
h3.human { color: #1f3d6b; background: #eef2f8; padding: 6pt; border-bottom: 0; }
h3.guidance { color: #4a3a1a; }
h3.safety { color: #4a2a2a; }
h4 { font-size: 10pt; margin: 10pt 0 4pt; }
table.kv { width: 100%; border-collapse: collapse; margin: 0 0 8pt; }
table.kv td { vertical-align: top; padding: 2pt 4pt 2pt 0; }
table.kv td.label { width: 32%; color: #555; }
.para { white-space: pre-wrap; word-wrap: break-word; margin: 0 0 8pt; }
.muted { color: #666; }
.disclaimer { font-style: italic; color: #444; margin: 0 0 8pt; }
.uncertain { color: #8a5a00; background: #fff6e0; padding: 6pt; }
a { color: #1a1a1a; text-decoration: none; }
</style>
</head>
<body>
{$body}
</body>
</html>
HTML;
    }

    /**
     * @param  array<string, string|null>  $rows
     */
    private function kv(array $rows): string
    {
        $html = '<table class="kv">';
        foreach ($rows as $label => $value) {
            $html .= '<tr><td class="label">'.$this->e($label).'</td><td>'
                .$this->e($this->display($value)).'</td></tr>';
        }

        return $html.'</table>';
    }

    private function para(mixed $value): string
    {
        $text = $this->display($value);
        if ($text === 'Not provided' || $text === '') {
            return '<p class="muted">Not provided</p>';
        }

        return '<div class="para">'.$this->e($text).'</div>';
    }

    private function display(mixed $value): string
    {
        if ($value === null) {
            return 'Not provided';
        }

        $string = trim((string) $value);

        return $string === '' ? 'Not provided' : $string;
    }

    private function displayLabel(mixed $value): string
    {
        $string = $this->display($value);

        return match ($string) {
            'unverified' => 'Unverified',
            'reported_by_user' => 'Reported by user',
            'verified_by_reviewer' => 'Verified by reviewer',
            default => $string,
        };
    }

    private function e(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
